// 孵蛋推荐预置辅助数据。
// 来源：B 站洛克王国手游 WIKI「孵蛋组别查询」页面（2026-07-16 更新）可见的蛋组清单与精灵条目。
// 这里只收录本仓库用于首屏验证和示例数据的安全子集；用户自定义非空字段不会被覆盖。

export const BILI_EGG_GROUP_SOURCE_URL = 'https://wiki.biligame.com/rocom/%E5%AD%B5%E8%9B%8B%E7%BB%84%E5%88%AB%E6%9F%A5%E8%AF%A2'

export const BILI_EGG_GROUP_NAMES = [
  '无法孵蛋',
  '动物组',
  '拟人组',
  '巨灵组',
  '魔力组',
  '天空组',
  '两栖组',
  '植物组',
  '大地组',
  '妖精组',
  '昆虫组',
  '软体组',
  '机械组',
  '海洋组',
  '飞龙组',
]

export const BREEDING_PRESET_BY_NAME = {
  迪莫: { eggGroups: ['无法孵蛋'], speciesGroup: '迪莫' },
  圣光迪莫: { eggGroups: ['无法孵蛋'], speciesGroup: '迪莫' },
  里奥: { eggGroups: ['无法孵蛋'], speciesGroup: '里奥' },
  灵羽勇士: { eggGroups: ['无法孵蛋'], speciesGroup: '里奥' },
  圣羽翼王: { eggGroups: ['无法孵蛋'], speciesGroup: '里奥' },
  小帕尔: { eggGroups: ['无法孵蛋'], speciesGroup: '小帕尔' },
  帕尔萨斯: { eggGroups: ['无法孵蛋'], speciesGroup: '小帕尔' },
  龙息帕尔: { eggGroups: ['无法孵蛋'], speciesGroup: '小帕尔' },
  绒绒: { eggGroups: ['无法孵蛋'], speciesGroup: '绒绒' },
  小绒茧: { eggGroups: ['无法孵蛋'], speciesGroup: '绒绒' },
  绒仙子: { eggGroups: ['无法孵蛋'], speciesGroup: '绒绒' },
  犀角鸟: { eggGroups: ['无法孵蛋'], speciesGroup: '犀角鸟' },
  光纤兽: { eggGroups: ['无法孵蛋'], speciesGroup: '犀角鸟' },
  疾光千兽: { eggGroups: ['无法孵蛋'], speciesGroup: '犀角鸟' },
  钨丝贝贝: { eggGroups: ['无法孵蛋'], speciesGroup: '钨丝贝贝' },
  辉光幕机: { eggGroups: ['无法孵蛋'], speciesGroup: '钨丝贝贝' },
  机幕方舟: { eggGroups: ['无法孵蛋'], speciesGroup: '钨丝贝贝' },
  凡雀: { eggGroups: ['无法孵蛋'], speciesGroup: '凡雀' },
  紫翎鹰: { eggGroups: ['无法孵蛋'], speciesGroup: '凡雀' },
  凡鹰: { eggGroups: ['无法孵蛋'], speciesGroup: '凡雀' },
  小雪人: { eggGroups: ['无法孵蛋'], speciesGroup: '小雪人' },
  雪怪: { eggGroups: ['无法孵蛋'], speciesGroup: '小雪人' },
  爆焰仔: { eggGroups: ['无法孵蛋'], speciesGroup: '爆焰仔' },
  爆焰喷喷: { eggGroups: ['无法孵蛋'], speciesGroup: '爆焰仔' },
  学院呱呱: { eggGroups: ['无法孵蛋'], speciesGroup: '学院呱呱' },

  火花: { eggGroups: ['魔力组', '巨灵组'], speciesGroup: '火花' },
  焰火: { eggGroups: ['魔力组', '巨灵组'], speciesGroup: '火花' },
  火神: { eggGroups: ['魔力组', '巨灵组'], speciesGroup: '火花' },
  水蓝蓝: { eggGroups: ['魔力组'], speciesGroup: '水蓝蓝' },
  波波拉: { eggGroups: ['魔力组'], speciesGroup: '水蓝蓝' },
  水灵: { eggGroups: ['魔力组'], speciesGroup: '水蓝蓝' },

  喵喵: { eggGroups: ['动物组', '拟人组'], speciesGroup: '喵喵' },
  喵呜: { eggGroups: ['动物组', '拟人组'], speciesGroup: '喵喵' },
  魔力猫: { eggGroups: ['动物组', '拟人组'], speciesGroup: '喵喵' },
  叶冕魔力猫: { eggGroups: ['动物组', '拟人组'], speciesGroup: '喵喵' },
  锥尾羊: { eggGroups: ['动物组'], speciesGroup: '锥尾羊' },
  铃兰羊: { eggGroups: ['动物组'], speciesGroup: '锥尾羊' },
  花影羚羊: { eggGroups: ['动物组'], speciesGroup: '锥尾羊' },
  小鼠獭: { eggGroups: ['动物组', '两栖组'], speciesGroup: '小鼠獭' },
  燕尾獭: { eggGroups: ['动物组'], speciesGroup: '小鼠獭' },
  卷胡巨獭: { eggGroups: ['动物组'], speciesGroup: '小鼠獭' },
  护主犬: { eggGroups: ['动物组'], speciesGroup: '护主犬' },
  音速犬: { eggGroups: ['动物组'], speciesGroup: '护主犬' },
  风暴战犬: { eggGroups: ['动物组'], speciesGroup: '护主犬' },
  绿耳松鼠: { eggGroups: ['动物组'], speciesGroup: '绿耳松鼠' },
  抱枕松鼠: { eggGroups: ['动物组'], speciesGroup: '绿耳松鼠' },
  蹦床松鼠: { eggGroups: ['动物组'], speciesGroup: '绿耳松鼠' },
  伏地兽: { eggGroups: ['动物组'], speciesGroup: '伏地兽' },
  贪食鼹: { eggGroups: ['动物组'], speciesGroup: '伏地兽' },
  巨噬针鼹: { eggGroups: ['动物组'], speciesGroup: '伏地兽' },
  电咩咩: { eggGroups: ['动物组'], speciesGroup: '电咩咩' },
  粉咩咩: { eggGroups: ['动物组'], speciesGroup: '电咩咩' },
  电球咩咩: { eggGroups: ['动物组'], speciesGroup: '电咩咩' },
  小星光: { eggGroups: ['动物组'], speciesGroup: '小星光' },
  星光狮: { eggGroups: ['动物组'], speciesGroup: '小星光' },
  小独角兽: { eggGroups: ['动物组', '巨灵组'], speciesGroup: '小独角兽' },
  白金独角兽: { eggGroups: ['动物组', '巨灵组'], speciesGroup: '小独角兽' },
  小黑猫: { eggGroups: ['动物组', '妖精组'], speciesGroup: '小黑猫' },
  黑猫巫师: { eggGroups: ['动物组', '妖精组'], speciesGroup: '小黑猫' },
  忽幽狸: { eggGroups: ['动物组', '拟人组'], speciesGroup: '忽幽狸' },
  影狸: { eggGroups: ['动物组', '拟人组'], speciesGroup: '忽幽狸' },
  恶魔狼: { eggGroups: ['动物组'], speciesGroup: '恶魔狼' },
  呼呼猪: { eggGroups: ['动物组'], speciesGroup: '呼呼猪' },
  獠牙猪: { eggGroups: ['动物组'], speciesGroup: '呼呼猪' },
  灵狐: { eggGroups: ['动物组'], speciesGroup: '灵狐' },
  九尾狐: { eggGroups: ['动物组'], speciesGroup: '灵狐' },
  尖嘴狐仙: { eggGroups: ['动物组'], speciesGroup: '灵狐' },
  松仔: { eggGroups: ['动物组'], speciesGroup: '松仔' },
  松叶羊: { eggGroups: ['动物组'], speciesGroup: '松仔' },
  针叶巡林: { eggGroups: ['动物组'], speciesGroup: '松仔' },
  小勇狮: { eggGroups: ['动物组'], speciesGroup: '小勇狮' },
  炽焰狮: { eggGroups: ['动物组'], speciesGroup: '小勇狮' },
  炽心勇狮: { eggGroups: ['动物组'], speciesGroup: '小勇狮' },
  小怂猫: { eggGroups: ['动物组'], speciesGroup: '小怂猫' },
  怒目怂猫: { eggGroups: ['动物组'], speciesGroup: '小怂猫' },
  海豹战士: { eggGroups: ['动物组'], speciesGroup: '海豹战士' },
  海豹船长: { eggGroups: ['动物组'], speciesGroup: '海豹战士' },
  奔波鼠: { eggGroups: ['动物组'], speciesGroup: '奔波鼠' },
  流浪鼠: { eggGroups: ['动物组'], speciesGroup: '奔波鼠' },
  呆小路: { eggGroups: ['动物组'], speciesGroup: '呆小路' },
  舞动路路: { eggGroups: ['动物组'], speciesGroup: '呆小路' },
  白发路路: { eggGroups: ['动物组'], speciesGroup: '呆小路' },
  逗逗: { eggGroups: ['动物组'], speciesGroup: '逗逗' },
  气球猫: { eggGroups: ['动物组'], speciesGroup: '气球猫' },
  梦想三三: { eggGroups: ['动物组'], speciesGroup: '梦想三三' },
  古钟蛇: { eggGroups: ['动物组'], speciesGroup: '古钟蛇' },
  寒音蛇: { eggGroups: ['动物组'], speciesGroup: '古钟蛇' },
  电动长颈鹿: { eggGroups: ['动物组'], speciesGroup: '电动长颈鹿' },
  奔乐鹿: { eggGroups: ['动物组'], speciesGroup: '电动长颈鹿' },
  爵士鹿: { eggGroups: ['动物组'], speciesGroup: '电动长颈鹿' },
  治愈兔: { eggGroups: ['动物组'], speciesGroup: '治愈兔' },
  红丝绒: { eggGroups: ['动物组'], speciesGroup: '治愈兔' },
  红绒十字: { eggGroups: ['动物组'], speciesGroup: '治愈兔' },
  优优: { eggGroups: ['动物组'], speciesGroup: '优优' },
  绒光优优: { eggGroups: ['动物组'], speciesGroup: '优优' },
  月牙雪熊: { eggGroups: ['动物组'], speciesGroup: '月牙雪熊' },
  火红尾: { eggGroups: ['动物组'], speciesGroup: '火红尾' },
  雅丹鬃: { eggGroups: ['动物组'], speciesGroup: '火红尾' },
  春团: { eggGroups: ['动物组'], speciesGroup: '春团' },
  春兔: { eggGroups: ['动物组'], speciesGroup: '春团' },
  春花兔: { eggGroups: ['动物组'], speciesGroup: '春团' },
  猴麦仔: { eggGroups: ['动物组'], speciesGroup: '猴麦仔' },
  音碟吼: { eggGroups: ['动物组'], speciesGroup: '猴麦仔' },
  炫光迪迪: { eggGroups: ['动物组'], speciesGroup: '炫光迪迪' },
  霹雳迪迪: { eggGroups: ['动物组'], speciesGroup: '炫光迪迪' },
  小鼓象: { eggGroups: ['动物组'], speciesGroup: '小鼓象' },
  巨鼓象: { eggGroups: ['动物组'], speciesGroup: '小鼓象' },
}

export const BREEDING_DEMO_OWNED = [
  { name: '喵喵', gender: 'female', nature: 'peaceful', shiny: 'yes', colorful: 'no', note: '孵蛋推荐示例：异色母本，用于测试异色优先孵蛋。' },
  { name: '魔力猫', gender: 'male', nature: 'relaxed', shiny: 'yes', colorful: 'yes', note: '孵蛋推荐示例：异色炫彩父本。' },
  { name: '锥尾羊', gender: 'female', nature: 'cheerful', shiny: 'yes', colorful: 'no', note: '孵蛋推荐示例：异色母本。' },
  { name: '花影羚羊', gender: 'male', nature: 'adamant', shiny: 'yes', colorful: 'yes', note: '孵蛋推荐示例：异色炫彩父本。' },
  { name: '小鼠獭', gender: 'female', nature: 'silent', shiny: 'yes', colorful: 'no', note: '孵蛋推荐示例：异色母本。' },
  { name: '卷胡巨獭', gender: 'male', nature: 'clever', shiny: 'yes', colorful: 'yes', note: '孵蛋推荐示例：异色炫彩父本。' },
  { name: '绿耳松鼠', gender: 'female', nature: 'steady', shiny: 'yes', colorful: 'no', note: '孵蛋推荐示例：异色母本。' },
  { name: '蹦床松鼠', gender: 'male', nature: 'clever', shiny: 'yes', colorful: 'yes', note: '孵蛋推荐示例：异色炫彩父本。' },
  { name: '护主犬', gender: 'female', nature: 'cheerful', shiny: 'yes', colorful: 'no', note: '孵蛋推荐示例：异色母本。' },
  { name: '音速犬', gender: 'male', nature: 'adamant', shiny: 'yes', colorful: 'yes', note: '孵蛋推荐示例：异色炫彩父本。' },
]
