// 孵蛋推荐预置辅助数据。
// 来源：B 站洛克王国手游 WIKI「蛋组计算器」页面（2026-06-16 更新）可见的蛋组清单与精灵条目。
// 这里只收录本仓库用于首屏验证和示例数据的安全子集；用户自定义非空字段不会被覆盖。

export const BILI_EGG_GROUP_SOURCE_URL = 'https://wiki.biligame.com/rocom/%E8%9B%8B%E7%BB%84%E8%AE%A1%E7%AE%97%E5%99%A8'

export const BILI_EGG_GROUP_NAMES = [
  '无法孵蛋',
  '动物组',
  '拟人组',
  '巨灵组',
  '魔力组',
  '天空组',
  '两栖组',
  '植物组',
  '大地组',
  '妖精组',
  '昆虫组',
  '软体组',
  '机械组',
  '海洋组',
  '龙组',
]

export const BREEDING_PRESET_BY_NAME = {
  迪莫: { eggGroups: ['无法孵蛋'], speciesGroup: '迪莫系' },
  圣光迪莫: { eggGroups: ['无法孵蛋'], speciesGroup: '迪莫系' },
  里奥: { eggGroups: ['无法孵蛋'], speciesGroup: '里奥系' },
  灵羽勇士: { eggGroups: ['无法孵蛋'], speciesGroup: '里奥系' },
  圣羽翼王: { eggGroups: ['无法孵蛋'], speciesGroup: '里奥系' },
  小帕尔: { eggGroups: ['无法孵蛋'], speciesGroup: '小帕尔系' },
  帕尔萨斯: { eggGroups: ['无法孵蛋'], speciesGroup: '小帕尔系' },
  龙息帕尔: { eggGroups: ['无法孵蛋'], speciesGroup: '小帕尔系' },
  绒绒: { eggGroups: ['无法孵蛋'], speciesGroup: '绒绒系' },
  小绒茧: { eggGroups: ['无法孵蛋'], speciesGroup: '绒绒系' },
  绒仙子: { eggGroups: ['无法孵蛋'], speciesGroup: '绒绒系' },
  犀角鸟: { eggGroups: ['无法孵蛋'], speciesGroup: '犀角鸟系' },
  光纤兽: { eggGroups: ['无法孵蛋'], speciesGroup: '犀角鸟系' },
  疾光千兽: { eggGroups: ['无法孵蛋'], speciesGroup: '犀角鸟系' },
  钨丝贝贝: { eggGroups: ['无法孵蛋'], speciesGroup: '钨丝贝贝系' },
  辉光幕机: { eggGroups: ['无法孵蛋'], speciesGroup: '钨丝贝贝系' },
  机幕方舟: { eggGroups: ['无法孵蛋'], speciesGroup: '钨丝贝贝系' },
  凡雀: { eggGroups: ['无法孵蛋'], speciesGroup: '凡雀系' },
  紫翎鹰: { eggGroups: ['无法孵蛋'], speciesGroup: '凡雀系' },
  凡鹰: { eggGroups: ['无法孵蛋'], speciesGroup: '凡雀系' },
  小雪人: { eggGroups: ['无法孵蛋'], speciesGroup: '小雪人系' },
  雪怪: { eggGroups: ['无法孵蛋'], speciesGroup: '小雪人系' },
  爆焰仔: { eggGroups: ['无法孵蛋'], speciesGroup: '爆焰仔系' },
  爆焰喷喷: { eggGroups: ['无法孵蛋'], speciesGroup: '爆焰仔系' },
  学院呱呱: { eggGroups: ['无法孵蛋'], speciesGroup: '学院呱呱系' },

  喵喵: { eggGroups: ['动物组'], speciesGroup: '喵喵系' },
  喵呜: { eggGroups: ['动物组'], speciesGroup: '喵喵系' },
  魔力猫: { eggGroups: ['动物组'], speciesGroup: '喵喵系' },
  叶冕魔力猫: { eggGroups: ['动物组'], speciesGroup: '喵喵系' },
  锥尾羊: { eggGroups: ['动物组'], speciesGroup: '锥尾羊系' },
  铃兰羊: { eggGroups: ['动物组'], speciesGroup: '锥尾羊系' },
  花影羚羊: { eggGroups: ['动物组'], speciesGroup: '锥尾羊系' },
  小鼠獭: { eggGroups: ['动物组'], speciesGroup: '小鼠獭系' },
  燕尾獭: { eggGroups: ['动物组'], speciesGroup: '小鼠獭系' },
  卷胡巨獭: { eggGroups: ['动物组'], speciesGroup: '小鼠獭系' },
  护主犬: { eggGroups: ['动物组'], speciesGroup: '护主犬系' },
  音速犬: { eggGroups: ['动物组'], speciesGroup: '护主犬系' },
  风暴战犬: { eggGroups: ['动物组'], speciesGroup: '护主犬系' },
  绿耳松鼠: { eggGroups: ['动物组'], speciesGroup: '绿耳松鼠系' },
  抱枕松鼠: { eggGroups: ['动物组'], speciesGroup: '绿耳松鼠系' },
  蹦床松鼠: { eggGroups: ['动物组'], speciesGroup: '绿耳松鼠系' },
  伏地兽: { eggGroups: ['动物组'], speciesGroup: '伏地兽系' },
  贪食鼹: { eggGroups: ['动物组'], speciesGroup: '伏地兽系' },
  巨噬针鼹: { eggGroups: ['动物组'], speciesGroup: '伏地兽系' },
  电咩咩: { eggGroups: ['动物组'], speciesGroup: '电咩咩系' },
  粉咩咩: { eggGroups: ['动物组'], speciesGroup: '电咩咩系' },
  电球咩咩: { eggGroups: ['动物组'], speciesGroup: '电咩咩系' },
  小星光: { eggGroups: ['动物组'], speciesGroup: '小星光系' },
  星光狮: { eggGroups: ['动物组'], speciesGroup: '小星光系' },
  小独角兽: { eggGroups: ['动物组'], speciesGroup: '小独角兽系' },
  白金独角兽: { eggGroups: ['动物组'], speciesGroup: '小独角兽系' },
  小黑猫: { eggGroups: ['动物组'], speciesGroup: '小黑猫系' },
  黑猫巫师: { eggGroups: ['动物组'], speciesGroup: '小黑猫系' },
  忽幽狸: { eggGroups: ['动物组'], speciesGroup: '忽幽狸系' },
  影狸: { eggGroups: ['动物组'], speciesGroup: '忽幽狸系' },
  恶魔狼: { eggGroups: ['动物组'], speciesGroup: '恶魔狼系' },
  呼呼猪: { eggGroups: ['动物组'], speciesGroup: '呼呼猪系' },
  獠牙猪: { eggGroups: ['动物组'], speciesGroup: '呼呼猪系' },
  灵狐: { eggGroups: ['动物组'], speciesGroup: '灵狐系' },
  九尾狐: { eggGroups: ['动物组'], speciesGroup: '灵狐系' },
  尖嘴狐仙: { eggGroups: ['动物组'], speciesGroup: '灵狐系' },
  松仔: { eggGroups: ['动物组'], speciesGroup: '松仔系' },
  松叶羊: { eggGroups: ['动物组'], speciesGroup: '松仔系' },
  针叶巡林: { eggGroups: ['动物组'], speciesGroup: '松仔系' },
  小勇狮: { eggGroups: ['动物组'], speciesGroup: '小勇狮系' },
  炽焰狮: { eggGroups: ['动物组'], speciesGroup: '小勇狮系' },
  炽心勇狮: { eggGroups: ['动物组'], speciesGroup: '小勇狮系' },
  小怂猫: { eggGroups: ['动物组'], speciesGroup: '小怂猫系' },
  怒目怂猫: { eggGroups: ['动物组'], speciesGroup: '小怂猫系' },
  海豹战士: { eggGroups: ['动物组'], speciesGroup: '海豹战士系' },
  海豹船长: { eggGroups: ['动物组'], speciesGroup: '海豹战士系' },
  奔波鼠: { eggGroups: ['动物组'], speciesGroup: '奔波鼠系' },
  流浪鼠: { eggGroups: ['动物组'], speciesGroup: '奔波鼠系' },
  呆小路: { eggGroups: ['动物组'], speciesGroup: '呆小路系' },
  舞动路路: { eggGroups: ['动物组'], speciesGroup: '呆小路系' },
  白发路路: { eggGroups: ['动物组'], speciesGroup: '呆小路系' },
  逗逗: { eggGroups: ['动物组'], speciesGroup: '逗逗系' },
  气球猫: { eggGroups: ['动物组'], speciesGroup: '气球猫系' },
  梦想三三: { eggGroups: ['动物组'], speciesGroup: '梦想三三系' },
  古钟蛇: { eggGroups: ['动物组'], speciesGroup: '古钟蛇系' },
  寒音蛇: { eggGroups: ['动物组'], speciesGroup: '古钟蛇系' },
  电动长颈鹿: { eggGroups: ['动物组'], speciesGroup: '电动长颈鹿系' },
  奔乐鹿: { eggGroups: ['动物组'], speciesGroup: '电动长颈鹿系' },
  爵士鹿: { eggGroups: ['动物组'], speciesGroup: '电动长颈鹿系' },
  治愈兔: { eggGroups: ['动物组'], speciesGroup: '治愈兔系' },
  红丝绒: { eggGroups: ['动物组'], speciesGroup: '治愈兔系' },
  红绒十字: { eggGroups: ['动物组'], speciesGroup: '治愈兔系' },
  优优: { eggGroups: ['动物组'], speciesGroup: '优优系' },
  绒光优优: { eggGroups: ['动物组'], speciesGroup: '优优系' },
  月牙雪熊: { eggGroups: ['动物组'], speciesGroup: '月牙雪熊系' },
  火红尾: { eggGroups: ['动物组'], speciesGroup: '火红尾系' },
  雅丹鬃: { eggGroups: ['动物组'], speciesGroup: '火红尾系' },
  春团: { eggGroups: ['动物组'], speciesGroup: '春团系' },
  春兔: { eggGroups: ['动物组'], speciesGroup: '春团系' },
  春花兔: { eggGroups: ['动物组'], speciesGroup: '春团系' },
  猴麦仔: { eggGroups: ['动物组'], speciesGroup: '猴麦仔系' },
  音碟吼: { eggGroups: ['动物组'], speciesGroup: '猴麦仔系' },
  炫光迪迪: { eggGroups: ['动物组'], speciesGroup: '炫光迪迪系' },
  霹雳迪迪: { eggGroups: ['动物组'], speciesGroup: '炫光迪迪系' },
  小鼓象: { eggGroups: ['动物组'], speciesGroup: '小鼓象系' },
  巨鼓象: { eggGroups: ['动物组'], speciesGroup: '小鼓象系' },
}

export const BREEDING_DEMO_OWNED = [
  { name: '喵喵', gender: 'female', nature: 'peaceful', shiny: 'yes', colorful: 'no', note: '孵蛋推荐示例：异色母本，用于测试异色优先孵蛋。' },
  { name: '魔力猫', gender: 'male', nature: 'relaxed', shiny: 'yes', colorful: 'yes', note: '孵蛋推荐示例：异色炫彩父本。' },
  { name: '锥尾羊', gender: 'female', nature: 'cheerful', shiny: 'yes', colorful: 'no', note: '孵蛋推荐示例：异色母本。' },
  { name: '花影羚羊', gender: 'male', nature: 'adamant', shiny: 'yes', colorful: 'yes', note: '孵蛋推荐示例：异色炫彩父本。' },
  { name: '小鼠獭', gender: 'female', nature: 'silent', shiny: 'yes', colorful: 'no', note: '孵蛋推荐示例：异色母本。' },
  { name: '卷胡巨獭', gender: 'male', nature: 'clever', shiny: 'yes', colorful: 'yes', note: '孵蛋推荐示例：异色炫彩父本。' },
  { name: '绿耳松鼠', gender: 'female', nature: 'steady', shiny: 'yes', colorful: 'no', note: '孵蛋推荐示例：异色母本。' },
  { name: '蹦床松鼠', gender: 'male', nature: 'clever', shiny: 'yes', colorful: 'yes', note: '孵蛋推荐示例：异色炫彩父本。' },
  { name: '护主犬', gender: 'female', nature: 'cheerful', shiny: 'yes', colorful: 'no', note: '孵蛋推荐示例：异色母本。' },
  { name: '音速犬', gender: 'male', nature: 'adamant', shiny: 'yes', colorful: 'yes', note: '孵蛋推荐示例：异色炫彩父本。' },
]
